#Aplikasi KAL

##Page rank
###algoritma

PageRank adalah algoritma yang dikembangkan oleh Larry Page dan Sergey Brin, pendiri Google, untuk menentukan peringkat halaman web dalam hasil mesin pencari. Algoritma ini digunakan untuk mengukur pentingnya halaman web berdasarkan jumlah dan kualitas tautan yang mengarah ke halaman tersebut. PageRank didasarkan pada gagasan bahwa halaman web yang lebih penting cenderung menerima lebih banyak tautan dari halaman web lainnya.

Cara kerjanya secara singkat adalah sebagai berikut:

In [ ]:
import numpy as np

a = np.array([[0, 0, 1, 0.5], [1/3, 0, 0, 0], [1/3, 0.5, 0, 0.5], [1/3, 0.5, 0, 0]])
v = np.array([[0.25], [0.25], [0.25], [0.25]])

In [ ]:
av1 = a @ v
print(av1, '\n')

av2 = a @ av1
print(av2, '\n')

av3 = a @ av2
print(av3, '\n')

av4 = a @ av3
print(av4, '\n')

av5 = a @ av4
print(av5, '\n')

av6 = a @ av5
print(av6, '\n')

av7 = a @ av6
print(av7, '\n')

av8 = a @ av7
print(av8, '\n')

[[0.375     ]
 [0.08333333]
 [0.33333333]
 [0.20833333]] 

[[0.4375    ]
 [0.125     ]
 [0.27083333]
 [0.16666667]] 

[[0.35416667]
 [0.14583333]
 [0.29166667]
 [0.20833333]] 

[[0.39583333]
 [0.11805556]
 [0.29513889]
 [0.19097222]] 

[[0.390625  ]
 [0.13194444]
 [0.28645833]
 [0.19097222]] 

[[0.38194444]
 [0.13020833]
 [0.29166667]
 [0.19618056]] 

[[0.38975694]
 [0.12731481]
 [0.29050926]
 [0.19241898]] 

[[0.38671875]
 [0.12991898]
 [0.28978588]
 [0.19357639]] 



In [ ]:
import numpy as np
A = np.array([[0,0,1,1/2],[1/3,0,0,0],[1/3,1/2,0,1/2],[1/3,1/2,0,0]])
V0 = np.array([[0.25],[0.25],[0.25],[0.25]])
V1 = A@V0
V2 = A@V1
V3 = A@V2
V4 = A@V3
V5 = A@V4
V6 = A@V5
V7 = A@V6
V8 = A@V7
print(V8)
V0 = np.array([[0.34],[0.16],[0.18],[0.32]])
iterasi = 1
while True:
  error = 0.01
  Vn = A@V0
  total = 0
  for i in range(len(V0)):
    total += Vn[i][0] - V0[i][0]
  V0 = Vn
  if total == 0:
    break
  iterasi += 1
print(iterasi)
print(Vn)
print(total)
print(2**(1/2))


[[0.38671875]
 [0.12991898]
 [0.28978588]
 [0.19357639]]
3
[[0.35166667]
 [0.15      ]
 [0.29166667]
 [0.20666667]]
0.0
1.4142135623730951
