# determinan
## sifat sifat
### 1.
determinan dari matriks identitas adalah 1
contohnya ada pada matrik Z dan Y sebagai matriks identitas yang determinannya adalah 1

### 2.
menukar/merubah baris akan merubah tanda pada determinan
contohnya ada pada matrik C dan D yang hasilnya adalah perubahan tanda pada determinannya yang sebelumnya negatif menjadi  ataupu sebaliknya

### 3.
jika di suatu matriks pada suatu baris/kolom merupakan kelipatan dari baris/kolom yang lain maka matriks itu punya determinan == 0
contoh ada pada matriks E dan F dimana di matrik E ada baris yang kelipatan lainnya dan di matrik
dan di matrik F ada kolom yang merupakan kelipatan dari kolom lainnya

### 4.
jika suatu matrik adalah suatu kelipatan dari matriks lainnya cara menghitung determinanya adalah dengan menghitung
jumlah kelipatannya
kemudian dipangkatkan dengan baris dan kolom sebagai pangkat dan hasilnya dikalikan dengan hasil determinan
contohnya ada pada matriks D dan G yang kalau dituliskan maka:
2^3*3 dimana 2 adalah kelipatan dari matriks G terhadap matrik D dan pangkat 3 adalah jumlah baris da kolom  dan dikali 3 adalah determinan dari Matrik D dan hasilnya adalah determinan matrik G

### 5.
jika suatu baris/kolom dikalikan dengan suatu konstanta tertentu maka hasilnya adalah konstanta dikalikan dengan determinan  matriks tersebut  contohnya ada pada matrik A, I dan B yang dimana matrik I adalah perkalian konstanta dengan suatu baris dan matrik B perkalian dengan konstanta dengan suatu kolom dan hasilnya adalah determinan A*konstanta

### 6.
jika sebuah matrik matriks memiliki baris yang sama maka hasil dari menambahkan baris lainnya  adalah matriks dengan determinannya = determinan matriks pertama + determinan matriks kedua
ccontohnya ada pada matriks A, J dan K dimana baris kedua matriks A dan J sama dan dengan menambahkan baris lainnya maka akan menghasilkan matrik K dengan determinannya = determinan A + determinan J

### 7.
jika ada suatu matrik segitiga atas maka determinannya adalah hasil perkalian dari diagonalnya seperti pada contoh matriks L


### 8.
jika ada suatu matrik yang merupakan hasil perkalian matriks maka determin dari matrik hasil perkalian tersebut adalah perkalian kedua determinan matriks awal

In [ ]:
# importing Numpy package
import numpy as np

# creating a 2X2 Numpy matrix
Z = np.array([[1, 0], [0, 1]])
Y = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
C = np.array([[1, 2, 1], [3, 1, 2], [2, 1, 2]])
D = np.array([[3, 1, 2], [1, 2, 1], [2, 1, 2]])
E = np.array([[1, 2, 1], [2, 4, 2], [2, 1, 2]])
F = np.array([[1, 2, 2], [2, 4, 3], [1, 2, 3]])
G = np.array([[6, 2, 4], [2, 4, 2], [4, 2, 4]])
A = np.array([[3, 4], [2, 1]])
I = np.array([[6, 4], [4, 1]])
B = np.array([[6, 8], [2, 1]])
J = np.array([[4, 1], [2, 1]])
K = np.array([[7, 5], [2, 1]])
L = np.array([[4, 2, 1], [0, 1, 4], [0, 0, 2]])


# calculating the determinant of matrix

print(Z)
print("Z",np.round(np.linalg.det(Z)))
print(Y)
print("Y",np.round(np.linalg.det(Y)))
print(C)
print("C",np.round(np.linalg.det(C)))
print(D)
print("D",np.round(np.linalg.det(D)))
print(E)
print("E",np.round(np.linalg.det(E)))
print(F)
print("F",np.round(np.linalg.det(F)))
print(G)
print("G",np.round(np.linalg.det(G)))
print(A)
print("A",np.round(np.linalg.det(A)))
print(I)
print("I",np.round(np.linalg.det(I)))
print(B)
print("B",np.round(np.linalg.det(B)))
print(J)
print("J",np.round(np.linalg.det(J)))
print(K)
print("K",np.round(np.linalg.det(K)))
print(L)
print("L",np.round(np.linalg.det(L)))



[[1 0]
 [0 1]]
Z 1.0
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Y 1.0
[[1 2 1]
 [3 1 2]
 [2 1 2]]
C -3.0
[[3 1 2]
 [1 2 1]
 [2 1 2]]
D 3.0
[[1 2 1]
 [2 4 2]
 [2 1 2]]
E 0.0
[[1 2 2]
 [2 4 3]
 [1 2 3]]
F 0.0
[[6 2 4]
 [2 4 2]
 [4 2 4]]
G 24.0
[[3 4]
 [2 1]]
A -5.0
[[6 4]
 [4 1]]
I -10.0
[[6 8]
 [2 1]]
B -10.0
[[4 1]
 [2 1]]
J 2.0
[[7 5]
 [2 1]]
K -3.0
[[4 2 1]
 [0 1 4]
 [0 0 2]]
L 8.0
