#tugas 3
##matrik infers
###sifat sifat matrik invers
###mencari invers dengan eliminasi gauss jordan
###solusi sistem persamaan linier  denan marik invers
buat soal sistem persamaan linier 6 variabel

####matrik invers

Invers sendiri dapat diartikan sebagai lawan dari sesuatu (kebalikan). Jika suatu matriks memiliki invers, dapat dikatakan matriks tersebut adalah matriks nonsingular. Sebaliknya, jika suatu matriks tidak memiliki invers, maka matriks tersebut merupakan matriks singular.


Invers matriks adalah sebuah kebalikan (invers) dari kedua matriks. Apabila matriks tersebut dikalikan akan menghasilkan matriks persegi (AB = BA = |). Simbol dari invers matriks adalah pangkat -1 dan terletak di atas hurufnya. Sebagai contoh, matriks B adalah invers matriks A sehingga ditulis B = A–1 dan matriks A adalah invers dari matriks B ditulis A = B-1. Matriks A dan B merupakan dua matriks yang saling invers (berkebalikan).

#### sifat sifat matrik invers
suatu matrik dapat dikatakan matriks invers dari suatu matrik adalah ketika matrik tersebut dikalikan dengan matrik invernya menghasilkan

ika A adalah matriks kuadrat, dan jika kita dapat mencari matriks B sehingga AB = BA = I, maka A dikatakan dapat dibalik (invertible) dan B dinamakan invers (inverse) dari A.

jika suatu matriks A memiliki invers (yaitu, A adalah matriks nonsingular), dan matriks B adalah inversnya, maka A dikalikan dengan B akan menghasilkan matriks identitas

#### mencari invers dengan eliminasi gauss jordan

di sini saya akan mencari  ivers eliminasi gauss jordan

menurut gauss jordan :

(A|I)(A-1)

Di mana A = Matriks

I         = Matriks identitas

A-1       =  Invers Matriks

misalnya kita mau mencari invers dari sebuah matriks dengan ordo 3x3
contoh :

A
 \begin{bmatrix}
    1 &2& 3\\
    0& 1& 4\\
    5& 6 & 0
    \end{bmatrix}

I
 \begin{bmatrix}
    1 &0& 0\\
    0& 1& 0\\
    0& 0 & 1
    \end{bmatrix}
setelah itu kita gunakan eliminasi geuss jordan
 \begin{bmatrix}
    1 &2& 3|1&0&0\\
    0& 1& 4|0&1&0\\
    5& 6 & 0|0&0&1
    \end{bmatrix}
untuk mencari invers,caranya matriks identitasnya bisa ada disebelah kiri, terserah baris berapa mau di tambahin/dikurangin/dikali/dibagi sama baris keberapa.penyelesaiannya:

sekarang kurangkan baris ketiga dengan 5x baris pertama, maksud dari baris pertama dikalikan 5 dulu baru abis itu buat ngurangin baris ke tiga hasilnya :
 \begin{bmatrix}
    1 &2& 3|1&0&0\\
    0& 1& 4|0&1&0\\
    0& -4& -15|-5&0&1
    \end{bmatrix}
dari matriks diatas,tambahkan baris ke tiga dengan 4 kali baris kedua. hasilnya :
\begin{bmatrix}
    1 &2& 3|1&0&0\\
    0& 1& 4|0&1&0\\
    0& 0& 1|5&4&1
    \end{bmatrix}
selanjutnya kurangkan baris kedua dengan 4x baris ketiga.
dan kita kurangkan juga baris pertama dengan 3x baris ketiga. hasilnya:
\begin{bmatrix}
    1 &2& 0|16&-12&-3\\
    0& 1& 0|20&-15&-4\\
    0& 0& 1|-5&4&1
    \end{bmatrix}
langkah terakhir tinggal kurangkan baris pertama dengan 2x baris kedua.hasilnya :
\begin{bmatrix}
    1 &0& 0|-24&18&5\\
    0& 1& 0|20&-15&-4\\
    0& 0& 1|-5&4&1
    \end{bmatrix}
yang ada disebelah kanan adalah invers dari matrik A.
jadi invers matriknya:

A-1
\begin{bmatrix}
    -24&18&5\\
    20&-15&-4\\
    -5&4&1
    \end{bmatrix}
gauss jordan elimination juga bisa digunakan untuk mencari invers dari matriks dengan ordo yang lainnya. misalnya ordo 4x4, ordo 5x5, ordo 6x6, dan lain sebagainya.


####solusi persammaan linier dengan matrik invers

1. **Sistem Persamaan Linear**: Sistem persamaan linear adalah kumpulan persamaan linear yang melibatkan beberapa variabel. Solusi dari sistem persamaan linear adalah nilai-nilai variabel yang memenuhi semua persamaan dalam sistem tersebut.

2. **Matriks Koefisien dan Vektor Hasil**: Misalkan kita memiliki sistem persamaan linear dengan \( n \) persamaan dan \( n \) variabel. Matriks koefisien dari variabel-variabel \( x_1, x_2,.... x_n \) dapat kita susun menjadi matriks \( A \), dan vektor hasil dari persamaan-persamaan tersebut dapat kita susun menjadi vektor kolom \( B \).

  
   A =
   \begin{pmatrix}
   a_{11} & a_{12} & \ldots & a_{1n} \\
   a_{21} & a_{22} & \ldots & a_{2n} \\
   \vdots & \vdots & \ddots & \vdots \\
   a_{n1} & a_{n2} & \ldots & a_{nn} \\
   \end{pmatrix}
   , \
   
   B =
   \begin{pmatrix}
   b_1 \\
   b_2 \\
   \vdots \\
   b_n \\
   \end{pmatrix}
  

3. **Matriks Invers**: Solusi dari sistem persamaan linear dapat ditemukan dengan menggunakan matriks invers. Jika matriks koefisien \( A \) memiliki invers, kita dapat mengalikan inversnya dengan vektor \( B \):

   \[ X = A-1.B]

   Di mana \( X \) adalah vektor kolom yang berisi solusi untuk setiap variabel.

4. **Ketersediaan Invers**: tidak semua matriks memiliki invers. Matriks \( A \) harus merupakan matriks persegi (jumlah baris sama dengan jumlah kolom) dan determinannya tidak boleh nol untuk memiliki invers. Jika matriks \( A \) tidak memiliki invers, maka sistem persamaan linear tersebut mungkin memiliki tidak ada solusi atau memiliki banyak solusi.

In [ ]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [ ]:
import numpy as np
x1 = 2
x2 = 3
x3 = 5
x4 = 2
x5 = 1
x6 = 2
B = np.array ([[40],[38],[30],[44],[49],[47]])
AB =np.array([[1,3,4,2,3,1,],[1,2,3,4,3,2],[2,1,1,5,2,3],[2,4,3,1,5,3],[2,4,4,3,5,1],[1,3,4,3,2,4]])
A=np.array([[1,0,0,0,0,0],[0,1,0,0,0,0],[0,0,1,0,0,0],[0,0,0,1,0,0],[0,0,0,0,1,0],[0,0,0,0,0,1]])

print(AB)

[[1 3 4 2 3 1]
 [1 2 3 4 3 2]
 [2 1 1 5 2 3]
 [2 4 3 1 5 3]
 [2 4 4 3 5 1]
 [1 3 4 3 2 4]]


In [ ]:
for i in range(len(AB)):
  for j in range(len(AB[i])):
    if i == j  :
      B = RowScale(B,i,1/AB[i][j])
      AB = RowScale(AB,i,1/AB[i][j])

    elif i > j:
      B = RowAdd(B,j,i,AB[j][j]*-AB[i][j])
      AB = RowAdd(AB,j,i,AB[j][j]*-AB[i][j])


for i in range(len(AB)):
  for j in range(len(AB[i])):
    if i < j:
      B = RowAdd(B,j,i,AB[j][j]*-AB[i][j])
      AB = RowAdd(AB,j,i,AB[j][j]*-AB[i][j])


print(np.round(AB))
print(np.round(B))

# for i in range(len(AB)):
    # for j in range(len(ab[i])):
      # if i == j:
        #


[[ 1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0. -0.]
 [-0. -0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0. -0.]
 [-0. -0. -0. -0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]]
[[2.]
 [3.]
 [5.]
 [2.]
 [1.]
 [2.]]


In [ ]:
A1 = RowAdd(A,0,1,-1)
print(A1,'\n')
A2 = RowAdd(A1,0,2,-2)
print(A2,'\n')
A3 = RowAdd(A2,0,3,-2)
print(A3,'\n')
A4 = RowAdd(A3,0,4,-2)
print(A4,'\n')
A5 = RowAdd(A4,0,5,-1)
print(A5,'\n')
A6 = RowAdd(A5,1,0,3)
print(A6,'\n')
A7 = RowAdd(A6,1,2,-5)
print(A7,'\n')
A8 = RowAdd(A7,1,3,-2)
print(A8,'\n')
A9 = RowAdd(A8,1,4,-2)
print(A9,'\n')
A10 = RowAdd(A9,3,2,-1)
print(A10,'\n')
A11 = RowAdd(A10,2,3,3)
print(A11,'\n')
A12 = RowAdd(A11,2,4,2)
print(A12,'\n')
A13 = RowAdd(A12,2,0,-1)
print(A13,'\n')
A14 = RowAdd(A13,2,1,1)
print(A14,'\n')
A15 = RowAdd(A14,5,3,14)
print(A15,'\n')
A16 = RowAdd(A15,3,0,-10)
print(A16,'\n')
A17 = RowAdd(A16,3,2,2)
print(A17,'\n')
A18 = RowAdd(A17,3,4,9)
print(A18,'\n')
A19 = RowAdd(A18,3,5,-1)
print(A19,'\n')
A20 = RowAdd(A19,5,4,9)
print(A20,'\n')
A21 = RowScale(A20,1,-1)
print(A21,'\n')
A22 = RowScale(A21,4,-1/16)
print(A22,'\n')
A23 = RowAdd(A22,4,5,-23)
print(A23,'\n')
A24 = RowAdd(A23,4,0,-246)
print(A24,'\n')
A25 = RowAdd(A24,4,1,-3)
print(A25,'\n')
A26 = RowAdd(A25,4,2,51)
print(A25,'\n')
A27 = RowAdd(A26,4,3,24)
print(A27,'\n')
A28 = RowScale(A27,5,-1/3.125)
print(A28,'\n')
A29 = RowAdd(A28,5,0,36.25)
print(A29,'\n')
A30 = RowAdd(A29,5,1,-5.375)
print(A30,'\n')
A31 = RowAdd(A30,5,2,-3.625)
print(A31,'\n')
A32 = RowAdd(A31,5,3,-5)
print(A32,'\n')
A33 = RowAdd(A32,5,4,1.125)
print(A33,'\n')

print(np.round(AB@A33))

[[ 1.  0.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]] 

[[ 1.  0.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.  0.]
 [-2.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]] 

[[ 1.  0.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.  0.]
 [-2.  0.  1.  0.  0.  0.]
 [-2.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]] 

[[ 1.  0.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.  0.]
 [-2.  0.  1.  0.  0.  0.]
 [-2.  0.  0.  1.  0.  0.]
 [-2.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]] 

[[ 1.  0.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.  0.]
 [-2.  0.  1.  0.  0.  0.]
 [-2.  0.  0.  1.  0.  0.]
 [-2.  0.  0.  0.  1.  0.]
 [-1.  0.  0.  0.  0.  1.]] 

[[-2.  3.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.  0.]
 [-2.  0.  1.  0.  0.  0.]
 [-2.  0.  0.  1.  0.  0.]
 [-2.  0.  0.  0.  1.  0.]
 [-1.  0.  0.  0.  0.  1.]] 

[[-2.  3. 

In [7]:
A = np.array ([[40],[38],[30],[44],[49],[47]])
A1 = RowAdd(A,1,1,-1)
print(A1,'\n')
A2 = RowAdd(A1,0,0,-2)
print(A2,'\n')
A3 = RowAdd(A2,0,3,-2)
print(A3,'\n')
A4 = RowAdd(A3,0,4,-2)
print(A4,'\n')
A5 = RowAdd(A4,0,5,-1)
print(A5,'\n')
A6 = RowAdd(A5,1,0,3)
print(A6,'\n')
A7 = RowAdd(A6,1,2,-5)
print(A7,'\n')
A8 = RowAdd(A7,1,3,-2)
print(A8,'\n')
A9 = RowAdd(A8,1,4,-2)
print(A9,'\n')
A10 = RowAdd(A9,3,2,-1)
print(A10,'\n')
A11 = RowAdd(A10,2,3,3)
print(A11,'\n')
A12 = RowAdd(A11,2,4,2)
print(A12,'\n')
A13 = RowAdd(A12,2,0,-1)
print(A13,'\n')
A14 = RowAdd(A13,2,1,1)
print(A14,'\n')
A15 = RowAdd(A14,5,3,14)
print(A15,'\n')
A16 = RowAdd(A15,3,0,-10)
print(A16,'\n')
A17 = RowAdd(A16,3,2,2)
print(A17,'\n')
A18 = RowAdd(A17,3,4,9)
print(A18,'\n')
A19 = RowAdd(A18,3,5,-1)
print(A19,'\n')
A20 = RowAdd(A19,5,4,9)
print(A20,'\n')
A21 = RowScale(A20,1,-1)
print(A21,'\n')
A22 = RowScale(A21,4,-1/16)
print(A22,'\n')
A23 = RowAdd(A22,4,5,-23)
print(A23,'\n')
A24 = RowAdd(A23,4,0,-246)
print(A24,'\n')
A25 = RowAdd(A24,4,1,-3)
print(A25,'\n')
A26 = RowAdd(A25,4,2,51)
print(A25,'\n')
A27 = RowAdd(A26,4,3,24)
print(A27,'\n')
A28 = RowScale(A27,5,-1/3.125)
print(A28,'\n')
A29 = RowAdd(A28,5,0,36.25)
print(A29,'\n')
A30 = RowAdd(A29,5,1,-5.375)
print(A30,'\n')
A31 = RowAdd(A30,5,2,-3.625)
print(A31,'\n')
A32 = RowAdd(A31,5,3,-5)
print(A32,'\n')
A33 = RowAdd(A32,5,4,1.125)
print(A33,'\n')

[[40.]
 [ 0.]
 [30.]
 [44.]
 [49.]
 [47.]] 

[[-40.]
 [  0.]
 [ 30.]
 [ 44.]
 [ 49.]
 [ 47.]] 

[[-40.]
 [  0.]
 [ 30.]
 [124.]
 [ 49.]
 [ 47.]] 

[[-40.]
 [  0.]
 [ 30.]
 [124.]
 [129.]
 [ 47.]] 

[[-40.]
 [  0.]
 [ 30.]
 [124.]
 [129.]
 [ 87.]] 

[[-40.]
 [  0.]
 [ 30.]
 [124.]
 [129.]
 [ 87.]] 

[[-40.]
 [  0.]
 [ 30.]
 [124.]
 [129.]
 [ 87.]] 

[[-40.]
 [  0.]
 [ 30.]
 [124.]
 [129.]
 [ 87.]] 

[[-40.]
 [  0.]
 [ 30.]
 [124.]
 [129.]
 [ 87.]] 

[[-40.]
 [  0.]
 [-94.]
 [124.]
 [129.]
 [ 87.]] 

[[ -40.]
 [   0.]
 [ -94.]
 [-158.]
 [ 129.]
 [  87.]] 

[[ -40.]
 [   0.]
 [ -94.]
 [-158.]
 [ -59.]
 [  87.]] 

[[  54.]
 [   0.]
 [ -94.]
 [-158.]
 [ -59.]
 [  87.]] 

[[  54.]
 [ -94.]
 [ -94.]
 [-158.]
 [ -59.]
 [  87.]] 

[[  54.]
 [ -94.]
 [ -94.]
 [1060.]
 [ -59.]
 [  87.]] 

[[-10546.]
 [   -94.]
 [   -94.]
 [  1060.]
 [   -59.]
 [    87.]] 

[[-10546.]
 [   -94.]
 [  2026.]
 [  1060.]
 [   -59.]
 [    87.]] 

[[-10546.]
 [   -94.]
 [  2026.]
 [  1060.]
 [  9481.]
 [    87.]] 

[[-1