# Aljabar matrik
- berikan penjelasan tentang apa itu matrik
- operasi matrik(pertambahan, pengurangan dan pemrkalian)
- buat program untuk mengalikan matrik A dan B
- pertambahan pengurangan perkalian dan transpose matrik
syaa disuruh bikin matrik A dan B ukuran 3X3 dan matrik c dengan unkuran 3x2
m x n adalah matrik A
n x k adalah matrik B

In [1]:
import numpy as np
import sympy as sy

In [ ]:
import numpy as np
A = np.array([[2,5,3],[2,6,3],[7,9,2]])
print(A)
B = np.array([[2,1,4],[7,3,6],[2,6,5]])
print(B)
C = np.array([[2,4],[3,6],[7,2]])
print(C)
D = np.array([[8,4,4],[2,5,6],[7,2,5]])
print(D)

y = np.array([[1,2,3],[4,5,6]])
print(y)
z = np.array([[1,2],[3,4],[5,6]])
print(z)

print(y@z)
print(A@C)

[[2 5 3]
 [2 6 3]
 [7 9 2]]
[[2 1 4]
 [7 3 6]
 [2 6 5]]
[[2 4]
 [3 6]
 [7 2]]
[[8 4 4]
 [2 5 6]
 [7 2 5]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[22 28]
 [49 64]]
[[40 44]
 [43 50]
 [55 86]]


Matriks adalah sekumpulan bilangan yang disusun berdasarkan baris dan kolom, serta ditempatkan di dalam tanda kurung.

## operasi matriks
### penjumlahan
 penjuamlahan matriks dapat dilakukan jika panjang baris dan kolomm kedua matriks sama

cara menjumlahkannya cukup menambahkan matriks pertama dan kedua pada tiap baris dan kolom yang sama

penjumlahan matrik memiliki sifat sifat:

Sifat komutatif

Pada sifat ini berlaku A + B = B + A.

Sifat asosiatif
Pada sifat ini berlaku (A + B) + C = A +(B + C)

Matriks nol

Pada sifat ini berlaku A + 0 = A.

Jika dijumlahkan dengan lawannya akan menghasilkan matriks
nol, yaitu A + (-A) = 0.
### pengurangan
 sama seperti penjumlahan hanya saja idkurangi
### perkalian
perkalian matriks hanya dapat dilakukan jika kolom matriks A sama dengan baris matrik B

matriks dari hasil perkalian matriks akan memiliki jumlah baris
yang sama dengan matrik pertama dan jumlah kolom yang sama dengan matrik kedua

perkalian matrik A x B berbeda dengan perkalian matrik B x A

perkalian matrik memiliki sifat sifat:

Sifat asosiatif

Pada sifat ini, berlaku (A × B) × C= A × (B × C)


Sifat distributif

Pada sifat ini, berlaku A × (B + C) = (A × B) + (A × C)
###transpose matrik
transpose matrik adalah matrik yang posisi baris dan kolomnya bertukar posisi  

transpose matriks biasanya ditandai dengan tanda pangkat t pada matriks tersebut

transpose matriks memiliki sifat sifat:

1. (PT)T = P

2. (P + Q)T = PT + QT

3. (P – Q)T = PT – QT

4. (KP)T = k.PT, di mana k = suatu konstanta

5. (PQ)T = PTQT

In [ ]:
result = [[0, 0 , 0],
          [0, 0 , 0],
          [0, 0 , 0]]

for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            result[i][j] += A[i][k] * B[k][j]



for row in result:
  print(row)
k = 0
Y = []
for i in range (len(A)):
  Z = []
  for j in range(len(B[0])):
    Z.append(A[i,0]*B[0,j]+A[i,1]*B[1,j]+A[i,2]*B[2,j])
  Y+=[Z]

Y=np.array(Y)
print(Y)
print(A@B)

[45, 35, 53]
[52, 38, 59]
[81, 46, 92]
[[45 35 53]
 [52 38 59]
 [81 46 92]]
[[45 35 53]
 [52 38 59]
 [81 46 92]]
